### ISSUE TITLE
undefined symbol: _ZN4hdf58datatype9TypeTraitIPKcE6createERKS3_ while using pniio 1.3.1

### ISSUE THREAD

**Issue by Ingvord** [pni-libraries/libpniio#127]
I am trying to write multiple string values into a dataset.

Xml structure looks like this:

```xml
<group type="NXentry" name="entry">
    <group type="NXlog" name="string">
        <field type="string" name="value">
            <dimensions rank="1">
                <dim value="2" index="0"/>
            </dimensions>
        </field>
        <field type="uint64" name="time"/>
    </group>
</group>
```

Client code:

```cpp
    auto dataset = get_object(env, jLong, jString);// basically gets Dataset using nexus::get_objects

    dataset.extent(0,1);
    auto size = dataset.dataspace().size();


    hdf5::dataspace::Hyperslab selection{{0},{1},{1},{1}};
    selection.offset(0,size - 1);
    dataset.write(value, selection);
```

Running my test gives me this error:

```
/opt/java/openjdk/bin/java: symbol lookup error: /tmp/b6bde250-f2d6-4c08-9517-0f259e390626/lib/native/x86_64-linux-gnu/libpniio_jni.so: undefined symbol: _ZN4hdf58datatype9TypeTraitIPKcE6createERKS3_
```

```
hzgpp05xenv% c++filt _ZN4hdf58datatype9TypeTraitIPKcE6createERKS3_
hdf5::datatype::TypeTrait<char const*>::create(char const* const&)
```

@jkotan do you have any idea how this could be fixed? Thanks

**Comment by jkotan** [comment]
Probably your `value` is of `char const* const` and h5cpp does not have `TypeTrait` for it. It better to use `std::string` or c-style array adapter  i.e. https://ess-dmsc.github.io/h5cpp/advanced/c_arrays.html

**Comment by jkotan** [comment]
BTW, if you want to have you string array only with two elements you do not have to execute `dataset.extent(0,1);` unless you wants to have three elements. You need call extent also when you skip `<dim value="2" index="0"/>`

**Comment by Ingvord** [comment]
Yei, that was that!

Thanks @jkotan 

PS when I skip `<dim value="2" index="0"/>` I get the JVM crash as in #128

**Comment by jkotan** [comment]
Hi Igor, now with PR #132 it should work.
