### ISSUE TITLE
Crash i.e. SIGSEGV calling nexus::xml::create_from_file on xml with duplicate entries

### ISSUE THREAD

**Issue by Ingvord** [pni-libraries/libpniio#128]
Hi,

I deliberately test duplicated entries in the xml:

```xml
<group type="NXentry" name="entry">
    <field type="string" name="string_scalar"/>
    <field type="string" name="string_scalar"/>
</group>
```  

Currently when trying to create a file from an xml I receive a fatal crash i.e. SIGSEGV

Code looks like this:

```cpp
try{
        auto file = hdf5::file::create(nativeString.value, hdf5::file::AccessFlags::TRUNCATE);
        auto root_group = file.root();

        pni::io::nexus::xml::create_from_file(root_group, templatePath);
} catch (const std::runtime_error& ex){
        jclass libpniioExceptionClass = env->FindClass("hzg/wpn/nexus/libpniio/jni/LibpniioException"); \
        env->ThrowNew(libpniioExceptionClass,ex.what()); \
}
```

The console output:

```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139995271722752:
  #000: ../../../src/H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../../src/H5Dint.c line 326 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: ../../../src/H5L.c line 1572 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: ../../../src/H5L.c line 1813 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../../src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../../src/H5L.c line 1608 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
#
free(): double free detected in tcache 2
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5331e68611, pid=1, tid=7
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x22611]  abort+0x1fd
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /tmp/fb03e974-1670-4e2d-98c9-b3dd95cb7265/core.1)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Here is full dump:
[hs_err_pid1.log](https://github.com/pni-libraries/libpniio/files/6675512/hs_err_pid1.log)

Expected behavior is to catch runtime_error and propagate it to Java

Could you please advise what is wrong here? Thanks

**Comment by jkotan** [comment]
Hi Igor,
setting fields or groups with the same name is not allowed for NXDL xml and hdf5/nexus files. Therefore you get the error.
I can try to add checks if the field/group exists and throw an PNI exception in this case. 
I tried by I cannot reproduce the segfault. 
Anyhow using  an xml with duplicate entries is a syntax error.

**Comment by Ingvord** [comment]
Yes, sure it is a syntax error. It is only because we generate xml files elsewhere.

The problem here is that I expect an exception, but get JVM crash

**Comment by Ingvord** [comment]
Looks like that might be unrelated as the JVM now crashes all the time with 

```
SIGSEGV (0xb) at pc=0x00007f73270109bd, pid=1, tid=8
```

**Comment by Ingvord** [comment]
I believe the root cause is `free(): double free detected in tcache 2` error that happens when pniio can not create file from xml template for whatever reason

**Comment by jkotan** [comment]
I've tried to run tests with `valgrind` but I could not get any  double free error. Do you have any c++ small sample which can give the error? Are you sure it is from library (not from Java wrapper)?

**Comment by jkotan** [comment]
Hi Igor, in #133 I've added checks if a field or agroup with a particular name already exists. So now you don't get an error message from hdf5 but runtime error from libpniio. If you need a new  debian/ubuntu package to try if you still have double free error with the PR  I will rebuild it.

**Comment by Ingvord** [comment]
@jkotan Thanks a lot! 

Yeah, I would love to test that. Currently I am using Debian 10 based docker container with installed packages from hdri repo:

```
RUN apt-get -qq update && export DEBIAN_FRONTEND=noninteractive && apt-get -qq install -y gnupg2 software-properties-common curl
RUN curl http://repos.pni-hdri.de/debian_repo.pub.gpg | apt-key add -
RUN add-apt-repository "deb http://repos.pni-hdri.de/apt/debian buster main" -y
RUN apt-get -qq update && export DEBIAN_FRONTEND=noninteractive && apt-get -qq dist-upgrade
RUN apt-get -qq update && export DEBIAN_FRONTEND=noninteractive && apt-get -qq install -y python3-sphinx apt-utils net-tools
RUN apt-get -qq install -y libpnicore1.1.1-dev libpnicore1.1.1 libpniio1.3.1-dev libpniio1.3.1 libh5cpp0.4.0-dev libh5cpp0.4.0 python3-numpy libhdf5-dev libboost-regex-dev libboost-program-options-dev libboost-system-dev libboost-date-time-dev libboost-filesystem-dev libblas-dev libatlas-base-dev cython3 python3-setuptools libboost-python-dev python3-numpy-abi9 g++ python3-h5py
RUN apt-get -qq install -y hdf5-plugin-bshuf hdf5-plugin-bz2 hdf5-plugin-lz4
```

If you could upload a new version there, say 1.3.2 I will be able to test it my Java wrapper

Thanks

**Comment by jkotan** [comment]
Hi Igor, I've just put the deb10 package to the NIMS and HDRI repositories. Since the patches do not changes API and ABI I've not released a new version of sources yet but add them as a patches to the debian package. The new patched version is `1.3.1-3+deb10u1~fsec` so you don't have to change anything in your Dockerfile but rebuild your container.

**Comment by Ingvord** [comment]
UPD: I tried with Debug build and it works as expected... so this error `free(): double free detected in tcache 2` happens only when I compile my library in Release mode

**Comment by jkotan** [comment]
Hi Igor, It usually happens when (local) variables are not initialized and used in the code lated e.g.
```c++
int main(){
    int a;
    cout << a << endl;
    return 0;
}
``` 
see https://stackoverflow.com/questions/36629053/getting-a-segmentation-fault-when-running-release-version-but-not-debug-version

**Comment by Ingvord** [comment]
I feel I have pinpointed the problem!

There is no return statement in my code, when throwing an exception into Java :

```cpp
if (!boost::filesystem::exists(templatePath)) {
    jclass libpniioExceptionClass = env->FindClass("hzg/wpn/nexus/libpniio/jni/LibpniioException");
    env->ThrowNew(libpniioExceptionClass, "template does not exists");
    //return -1; this was missing
}
```

Adding a `return` statement fixes the problem.

I will double check this and close the issue

Thanks for your help and fix

**Comment by Ingvord** [comment]
Seems to be ok now!
