### ISSUE TITLE
Unable to set extend dataset

### ISSUE THREAD

**Issue by Ingvord** [pni-libraries/libpniio#157]
Hi, 

while testing the new version (1.3.1) we also have encountered the following issue:

when we try to append or write into an opened file there is always an error:

```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140438913509120:
  #000: ../../../src/H5D.c line 906 in H5Dset_extent(): unable to set extend dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../../src/H5Dint.c line 2597 in H5D__set_extent(): no write intent on file
    major: Dataset
    minor: Write failed
```

I believe now that this due to the fact that when we write or append into a newly created file, datasets in it have parameters described in our xml template. While we open an existing file, datasets are defined based on the file structure not xml template, hence the error.

Is there any way to work around this?

**Comment by jkotan** [comment]
Hi @Ingvord, Could you please pass an example i.e. in which way you reopen the file.

**Comment by Ingvord** [comment]
Well, that is just that:

```cpp
auto file = hdf5::file::open(nativeString.value, false);
```

where nativeString.value - path to the file

**Comment by jkotan** [comment]
If you use  the h5cpp API you need to use flags, e.g.
```c++
auto file = hdf5::file::open("test_native.h5", hdf5::file::AccessFlags::READWRITE);
```

**Comment by Ingvord** [comment]
Yeah, that was that. Thanks!
