### ISSUE TITLE
get_objects method is slow

### ISSUE THREAD

**Issue by yuelongyu** [pni-libraries/libpniio#221]
when opening large number of fields (tried 60), get_objects method is slow.

```
nexus::DatasetList dsl = nexus::get_objects(m_file.root(),nexus::Path::from_string(field));
```

**Comment by jkotan** [comment]
Yes, thanks for your tests. As a workaround if the exact path in known it is good to  use 
```c++
hdf5::node::Dataset ds = m_file.root().get_dataset(hdf5::Path(field_path));
```

**Comment by jkotan** [comment]
It is mentioned in the documentation at https://pni-libraries.github.io/libpninexus/stable/users_guide/nexus_search.html
