### ISSUE TITLE
return value of size() method in field overflow

### ISSUE THREAD

**Issue by yuelongyu** [pni-libraries/libpniio#32]
I tried to use size() and image size to calculate total image numbers in the 2D field and got overflow.
The image size is 802896(1556*516). When there are 2674 images in the data field. The size() returns 2146943904. When it reaches 2675 images, it is already 18446744071562331120.
## some ouput:

size()|img size|expected index
2146943904|802896|2673
18446744071562331120|802896|1479583216

**Comment by yuelongyu** [comment]
The funny thing is even it reports error. I still get the expected image data in the Nexus file. At least, I check one hot pixel, it's still there.
The HDF file error:
----------------------------------------
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 139918491776768:
  #000: ../../../src/H5Dio.c line 231 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: ../../../src/H5Dio.c line 348 in H5D__pre_write(): file selection+offset not within extent
    major: Dataspace
    minor: Out of range

**Comment by eugenwintersberger** [comment]
Need to verify if this still exists with `h5cpp`.
