### ISSUE TITLE
cannot install it on Debian8

### ISSUE THREAD

**Issue by Tingfe** [pni-libraries/libpniio#34]
I tried to install the libpniio in my Debian8, but it always failed.
please see the process below:

tonny@debian:~/libpniio-1.0.0$ mkdir build
tonny@debian:~/libpniio-1.0.0$ cd build/
tonny@debian:~/libpniio-1.0.0/build$ cmake ../
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
No build type specified - default is RELEASE
-- Boost version: 1.60.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found HDF5: /usr/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
found GNU compiler ...
setup for release build ...
3.0.2
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Check size of long double
-- Check size of long double - done
-- checking for one of the modules 'pnicore'
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   program_options
--   system
--   regex
-- checking for one of the modules 'cppunit'
/usr/local/hdf5/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.8") 
multidim_attribute_test_bool_t.cpp;multidim_attribute_bool_t.xml;multidim_attribute_test_complex128.cpp;multidim_attribute_complex128.xml;multidim_attribute_test_complex64.cpp;multidim_attribute_complex64.xml;multidim_attribute_test_complex32.cpp;multidim_attribute_complex32.xml;multidim_attribute_test_float128.cpp;multidim_attribute_float128.xml;multidim_attribute_test_float64.cpp;multidim_attribute_float64.xml;multidim_attribute_test_float32.cpp;multidim_attribute_float32.xml;multidim_attribute_test_int64.cpp;multidim_attribute_int64.xml;multidim_attribute_test_uint64.cpp;multidim_attribute_uint64.xml;multidim_attribute_test_int32.cpp;multidim_attribute_int32.xml;multidim_attribute_test_uint32.cpp;multidim_attribute_uint32.xml;multidim_attribute_test_int16.cpp;multidim_attribute_int16.xml;multidim_attribute_test_uint16.cpp;multidim_attribute_uint16.xml;multidim_attribute_test_int8.cpp;multidim_attribute_int8.xml;multidim_attribute_test_uint8.cpp;multidim_attribute_uint8.xml
multidim_field_test_bool_t.cpp;multidim_field_bool_t.xml;multidim_field_test_complex128.cpp;multidim_field_complex128.xml;multidim_field_test_complex64.cpp;multidim_field_complex64.xml;multidim_field_test_complex32.cpp;multidim_field_complex32.xml;multidim_field_test_float128.cpp;multidim_field_float128.xml;multidim_field_test_float64.cpp;multidim_field_float64.xml;multidim_field_test_float32.cpp;multidim_field_float32.xml;multidim_field_test_int64.cpp;multidim_field_int64.xml;multidim_field_test_uint64.cpp;multidim_field_uint64.xml;multidim_field_test_int32.cpp;multidim_field_int32.xml;multidim_field_test_uint32.cpp;multidim_field_uint32.xml;multidim_field_test_int16.cpp;multidim_field_int16.xml;multidim_field_test_uint16.cpp;multidim_field_uint16.xml;multidim_field_test_int8.cpp;multidim_field_int8.xml;multidim_field_test_uint8.cpp;multidim_field_uint8.xml
-- Configuring done
CMake Warning (dev) at src/CMakeLists.txt:35 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "config.hpp" of target "pniio" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/tonny/libpniio-1.0.0/build
tonny@debian:~/libpniio-1.0.0/build$ make
Scanning dependencies of target formatter_objects
[  5%] Building CXX object src/formatters/CMakeFiles/formatter_objects.dir/scalar_format.cpp.o
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/scalar_format.cpp:26:
/usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/scalar_format.cpp:26:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/scalar_format.cpp:26:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
[  5%] Building CXX object src/formatters/CMakeFiles/formatter_objects.dir/vector_format.cpp.o
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/vector_format.cpp:26:
/usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/vector_format.cpp:26:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/karma/stream/detail/iterator_sink.hpp:13,
                 from /usr/local/include/boost/spirit/home/karma/stream/stream.hpp:24,
                 from /usr/local/include/boost/spirit/home/karma/stream.hpp:14,
                 from /usr/local/include/boost/spirit/home/karma.hpp:27,
                 from /usr/local/include/boost/spirit/include/karma.hpp:16,
                 from /home/tonny/libpniio-1.0.0/./include/pni/io/formatters/formatter.hpp:30,
                 from /home/tonny/libpniio-1.0.0/src/formatters/vector_format.cpp:26:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
[  5%] Built target formatter_objects
Scanning dependencies of target cbf_objects
[ 10%] Building CXX object src/cbf/CMakeFiles/cbf_objects.dir/cbf_reader.cpp.o
[ 10%] Building CXX object src/cbf/CMakeFiles/cbf_objects.dir/dectris_reader.cpp.o
[ 10%] Built target cbf_objects
Scanning dependencies of target fio_objects
[ 10%] Building CXX object src/fio/CMakeFiles/fio_objects.dir/fio_reader.cpp.o
[ 10%] Built target fio_objects
Scanning dependencies of target h5_objects
[ 10%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/attribute_imp.cpp.o
[ 10%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/attribute_utils.cpp.o
[ 15%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/field_factory.cpp.o
[ 15%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/field_imp.cpp.o
[ 15%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/file_imp.cpp.o
[ 15%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/group_imp.cpp.o
[ 21%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5dataspace.cpp.o
[ 21%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5datatype.cpp.o
[ 21%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5deflate_filter.cpp.o
[ 26%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5_error.cpp.o
[ 26%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5_error_stack.cpp.o
[ 26%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5filter.cpp.o
[ 31%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5link.cpp.o
[ 31%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/h5object_types.cpp.o
[ 31%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/hdf5_utilities.cpp.o
[ 36%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/object_imp.cpp.o
[ 36%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/string_utils.cpp.o
[ 36%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/selection.cpp.o
[ 42%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/nullterm_formatter.cpp.o
[ 42%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/charpad_formatter.cpp.o
[ 42%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/string_formatter.cpp.o
[ 47%] Building CXX object src/nx/h5/CMakeFiles/h5_objects.dir/string_formatter_factory.cpp.o
[ 47%] Built target h5_objects
Scanning dependencies of target xml_objects
[ 47%] Building CXX object src/nx/xml/CMakeFiles/xml_objects.dir/data_node.cpp.o
[ 47%] Building CXX object src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp: In function ‘bool pni::io::nx::xml::has_attribute(const node&, const string&)’:
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:124:16: error: cannot convert ‘boost::optional<const boost::property_tree::basic_ptree<std::basic_string<char>, std::basic_string<char> >&>’ to ‘bool’ in return
         return attr;
                ^
In file included from /usr/local/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
                 from /usr/local/include/boost/property_tree/detail/xml_parser_write.hpp:15,
                 from /usr/local/include/boost/property_tree/xml_parser.hpp:15,
                 from /home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:26:
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp: In instantiation of ‘class boost::property_tree::xml_parser::xml_writer_settings<char>’:
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:130:65:   required from here
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:38:35: error: ‘char’ is not a class, struct, or union type
  typedef typename Str::value_type Ch;
                                   ^
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:40:9: error: ‘char’ is not a class, struct, or union type
         xml_writer_settings(Ch inchar = Ch(' '),
         ^
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:50:33: error: ‘char’ is not a class, struct, or union type
         typename Str::size_type indent_count;
                                 ^
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp: In function ‘std::ostream& pni::io::nx::xml::operator<<(std::ostream&, const node&)’:
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:130:72: error: no matching function for call to ‘boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(char, int)’
         boost::property_tree::xml_writer_settings<char> settings('\t',1);
                                                                        ^
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:130:72: note: candidates are:
In file included from /usr/local/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
                 from /usr/local/include/boost/property_tree/detail/xml_parser_write.hpp:15,
                 from /usr/local/include/boost/property_tree/xml_parser.hpp:15,
                 from /home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:26:
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings()
     class xml_writer_settings
           ^
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 0 arguments, 2 provided
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: constexpr boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(const boost::property_tree::xml_parser::xml_writer_settings<char>&)
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: constexpr boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(boost::property_tree::xml_parser::xml_writer_settings<char>&&)
/usr/local/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:132:53: error: no matching function for call to ‘write_xml(std::ostream&, const node&, boost::property_tree::xml_parser::xml_writer_settings<char>&)’
         boost::property_tree::write_xml(o,n,settings);
                                                     ^
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:132:53: note: candidates are:
In file included from /home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:26:0:
/usr/local/include/boost/property_tree/xml_parser.hpp:124:10: note: template<class Ptree> void boost::property_tree::xml_parser::write_xml(const string&, const Ptree&, const std::locale&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&)
     void write_xml(const std::string &filename,
          ^
/usr/local/include/boost/property_tree/xml_parser.hpp:124:10: note:   template argument deduction/substitution failed:
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:132:53: note:   cannot convert ‘o’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const string& {aka const std::basic_string<char>&}’
         boost::property_tree::write_xml(o,n,settings);
                                                     ^
In file included from /home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:26:0:
/usr/local/include/boost/property_tree/xml_parser.hpp:100:10: note: void boost::property_tree::xml_parser::write_xml(std::basic_ostream<typename Ptree::key_type::value_type>&, const Ptree&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&) [with Ptree = boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> >; typename Ptree::key_type::value_type = char; typename Ptree::key_type = std::basic_string<char>]
     void write_xml(std::basic_ostream<
          ^
/usr/local/include/boost/property_tree/xml_parser.hpp:100:10: note:   no known conversion for argument 3 from ‘boost::property_tree::xml_parser::xml_writer_settings<char>’ to ‘const boost::property_tree::xml_parser::xml_writer_settingsstd::basic_string<char >&’
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp: In function ‘bool pni::io::nx::xml::has_attribute(const node&, const string&)’:
/home/tonny/libpniio-1.0.0/src/nx/xml/node.cpp:125:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
src/nx/xml/CMakeFiles/xml_objects.dir/build.make:77: recipe for target 'src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o' failed
make[2]: **\* [src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o] Error 1
CMakeFiles/Makefile2:1445: recipe for target 'src/nx/xml/CMakeFiles/xml_objects.dir/all' failed
make[1]: **\* [src/nx/xml/CMakeFiles/xml_objects.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Tingfe** [comment]
Debian7 is more suitable for this program. But we can use Debian7's source to solve this problem. and follow this guide https://github.com/pni-libraries/libpnicore/wiki/Installation

**Comment by eugenwintersberger** [comment]
Why didn'nt you use the debian packages for Debian 8?
