### ISSUE TITLE
pniio1.1.0 + H5DOwrite_chunk doesn't work on Debian 9

### ISSUE THREAD

**Issue by yuelongyu** [pni-libraries/libpniio#94]
When the file is created by pniio1.1.0 and the compressed data are written to the file by HDFDOWrite_chunk, error occurs on Debian 9. 
---
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139659112687424:
  #000: ../../../src/H5Dio.c line 225 in H5Dwrite(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
---
The file is still created but only with dark images in data field. When writing uncompressed data, it works without any problem.

**Comment by eugenwintersberger** [comment]
Can you please post the code snippet.

**Comment by yuelongyu** [comment]
Here are the part for writing compressed data. The dataset filed ID is fetched via PNIIO.
/**
         * @brief get field id
         * @param field
         * @return field id if successful; Otherwise it returns a negative value
         */
        template<typename T> 
            int GetFieldID(const T &field)
        {
            nxgroup g = field.parent();

            return H5Dopen(g.imp().object().id(),
                           field.name().c_str(),
                           H5P_DEFAULT);
        }

/**
         * @brief write 2D data
         * @param data
         * @param length of the data
         * @param nx
         * @param ny
         * @param frame number field name
         * @param error code field name
         * @param frame number
         * @param error code of the frame
         * @return error code.
         *         0: OK;
         */
        int Write2DCompressedData(string strDataFieldPath,vector<unsigned char>& vuchData,int nDataLength
                                  ,int nX, int nY
                                  ,string strFrameFieldPath,long lFrameNo
                                  ,string strErrCodeFieldPath,short shErrCode)
        {
            int nRet = 0;

            if((nRet = Write1DData<long>(lFrameNo,strFrameFieldPath)) != 0)
                return nRet;

            
            if((nRet = Write1DData<short>(shErrCode,strErrCodeFieldPath)) != 0)
                return nRet;

       
            //select field
            if((nRet = SelectField(strDataFieldPath)) != 0)
                return nRet;

        
            //get dataset field id
            int nID = GetFieldID(m_nxField);
            if(nID < 0)
                return GET_FIELD_ERROR;
        
            try
            {

                int nSize = GetWritePositionFor2DData(nX*nY);

                if(nSize == -1)
                    return INDEX_ERROR;

                long long unsigned int nOffset[3] = {static_cast<long long unsigned int>(nSize),
                                                     0,
                                                     0};
                //do chunk write
                int nRet = 0;

                nRet = H5DOwrite_chunk(nID //dataset id
                                       ,H5P_DEFAULT //not used
                                       ,0 //filter mask. 0 means with filter
                                       ,&nOffset[0] //logic position of the chunk's first element in dataspace
                                       ,nDataLength //data size
                                       ,reinterpret_cast<unsigned char*>(&vuchData[0]) // data
                                       );
		
                if(nRet < 0)
                    return WRITE_ERROR;
                
                m_nxFile.flush();

                H5Dclose(nID);
                
                return NO_ERROR;
            }
            catch(invalid_object_error& ie)
            {
                DisplayError(__FUNCTION__,"",INVALID_OBJECT_ERROR);
                return INVALID_OBJECT_ERROR;
            }
            catch(object_error& oe)
            {
                DisplayError(__FUNCTION__,"",OBJECT_ERROR);
                return OBJECT_ERROR;
            }
            catch(type_error& te)
            {
                DisplayError(__FUNCTION__,"",TYPE_ERROR);
                return TYPE_ERROR;
            }
            catch(size_mismatch_error& se)
            {
                DisplayError(__FUNCTION__,"",SIZE_MISMATCH_ERROR);
                return SIZE_MISMATCH_ERROR;
            }
            catch(io_error& ie)
            {
                DisplayError(__FUNCTION__,"",IO_ERROR);
                return IO_ERROR;
            }
        }

When writing compressed data on Debian 9. The following warning/error appears.
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139924163015232:
  #000: ../../../src/H5Dio.c line 225 in H5Dwrite(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type

I just put the project into stash repo in DESY. The whole project can be fetched from stash now.
https://stash.desy.de/scm/yy/filewriter.git

**Comment by yuelongyu** [comment]
As I mentioned in another ticket, in pniio1.2.0+h5cpp, with the static_cast<hid_t>(object), I may get the id of the dataset via h5cpp and this way works.
