### ISSUE TITLE
nexus::open_file error 

### ISSUE THREAD

**Issue by yuelongyu** [pni-libraries/libpniio#97]
When I try to open a nexus file with nexus::open_file(), I get following exception.

> HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139708546816896:
  #000: ../../../src/H5A.c line 695 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 524 in H5A__read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
  #002: ../../../src/H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failure to read data from attribute!
Aborted
It works without any problem with hdf5::file::open().
```C++
std::string filename = std::string("testcalib.nxs");
//hdf5::file::File file = hdf5::file::open(filename);
hdf5::file::File file = nexus::open_file(filename);
```
Enviroment:
Debian 9
libh5cpp.so.0.0.7
libpnicore.so.1.1.0 
libpniio.so.1.2.2

**Comment by jkotan** [comment]
it is related to https://github.com/ess-dmsc/h5cpp/issues/309
